robot_name: ABB
rotation_mode: xyz
rotation_as_degree: true
translations_scale: 0.001
is_robot_status_tcp_server: false
robot_model: Common
joint_lower_limit:
  - -180
  - -180
  - -180
  - -180
  - -180
  - -180
joint_upper_limit:
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
arm_port: 5000
with_control_center: false
robot_error_handler:
  collect_failure_case:
    error_id:
      []
flange_z_min: -500
disable_motion_planner_checker: false
visualizer_enable: false
robot_monitor_vis_enable: false
link_collision_check_enable:
  - false
  - false
  - false
  - false
  - true
  - true
  - true
  - false
manipulability_threshold: 0.017
invalid_grasp_filter_threshold: 15
invalid_grasp_max_num: 10
invalid_grasp_check_mode: object_id
sample_steplen_above_pose_to_pre_grasp: 0.03
sample_steplen_pre_grasp_to_grasp: 0.01
collision_objects: ~
arm_ip: 0.0.0.0
collision_check_mode: custom