robot_name: Dobot
rotation_mode: xyz
rotation_as_degree: true
translation_scale: 0.001
is_robot_status_tcp_server: false

robot_model: cr10as
joint_lower_limit:
  - -360
  - -360
  - -360
  - -360
  - -360
  - -360
joint_upper_limit:
  - 360
  - 360
  - 360
  - 360
  - 360
  - 360
joints_base: 
  - 0
  - 90
  - 0
  - 90
  - 0
  - 0